In [5]:
import numpy as np
def main(u,v):
    return np.cross(u,v)
#ML.1 page 264
A_u=np.array([1,-2,3])
A_v=np.array([1,3,1])
ans_A=main(A_u,A_v)
print("ML.1------------")
print("(a) u x v = ",ans_A)
B_u=np.array([1,0,3])
B_v=np.array([1,-1,2])
ans_B=main(B_u,B_v)
print("(b) u x v = ",ans_B)
C_u=np.array([1,-2,-3])
C_v=np.array([2,-1,2])
ans_C=main(C_u,C_v)
print("(c) u x v = ",ans_C)

ML.1------------
(a) u x v =  [-11   2   5]
(b) u x v =  [ 3  1 -1]
(c) u x v =  [-7 -8  3]


In [26]:
#page 209 exercise 20
def main(n):
    array_1=np.array([[2,4,6],[1,0,2],[2,3,-1]])
    array_2=np.array([2,0,-5])
    new_array=array_1
    if (n != -1):
        new_array[:,n]=array_2
    det=round(np.linalg.det(new_array))
    print("array--------")
    print(new_array)
    print("det of array =",det)
    return det
det_array=main(-1)
det_x=main(0)
det_y=main(1)
det_z=main(2)
x=det_x/det_array
y=det_y/det_array
z=det_z/det_array
print("x,y,z=%.2f,%.2f,%.2f"%(x,y,z))

array--------
[[ 2  4  6]
 [ 1  0  2]
 [ 2  3 -1]]
det of array = 26
array--------
[[ 2  4  6]
 [ 0  0  2]
 [-5  3 -1]]
det of array = -52
array--------
[[ 2  2  6]
 [ 1  0  2]
 [ 2 -5 -1]]
det of array = 0
array--------
[[ 2  4  2]
 [ 1  0  0]
 [ 2  3 -5]]
det of array = 26
x,y,z=-2.00,0.00,1.00
